name: Push to Gsheets

on:
  workflow_dispatch:
    inputs:
      event_id:
        required: true
        type: string

jobs:
  push_to_gsheets:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Push data to gsheets
        env:
          GSHEETS_SERVICE_ACCOUNT: ${{ secrets.GSHEETS_SECRET }}
          SHEET_URL: ${{ secrets.SHEET_URL }}
        run: |
          python main.py ${{ inputs.event_id }}
